stages:
  - build-app
  - deploy-prepare
  - deploy-validate
  - deploy-plan
  - deploy-execute
  - deploy-destroy

build:
  stage: build-app
  script:
    - buildah login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - ./build-docker.sh $CI_REGISTRY_IMAGE
  artifacts:
    paths:
      - mediawiki.version.auto.tfvars

include: /infra/.gitlab-ci.yml